/*
  SPILLS DATA
  Add your posts here to publish them to the world.
  Copy the object generated by the website and paste it into this array.
*/

const PUBLIC_SPILLS = [
    {
        id: 'post_welcome',
        title: 'welcome to scrap.',
        text: 'this is the start of something raw. a place for thoughts that don\'t fit anywhere else. no filters, just spills.',
        mood: '✦ inspired',
        color: '#7EB8DA',
        image: '',
        date: 'feb 15, 2026',
        author: 'adharshravi',
        timestamp: 1707990000000
    }
];
